name: Auto PR - into josh-Branch

on:
  push:
    branches:
    - "live"  # Support wildcard matching
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "live"                                 # If blank, default: triggered branch
        destination_branch: "josh-branch"                      # If blank, default: master
        pr_title: "Pulling ${{ github.event.commits[0].message }} into josh-Branch" # Title of pull request
        pr_body: ":crown: *An automated Sync"              # Full markdown support, requires pr_title to be set
        pr_template: ""   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: ""                         # Comma-separated list (no spaces)
        pr_assignee: "davasorus"                         # Comma-separated list (no spaces)
        pr_label: "automatic,automerge"                               # Comma-separated list (no spaces)
        pr_milestone: ""                       # Milestone name
        pr_draft: false                                    # Creates pull request as draft
        pr_allow_empty: false                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}
