name: DotNet 6.0 Build Status

on:
  push:
    branches: [ dev-branch ]
  pull_request:
    branches: [ live ]

jobs:
  build:

    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
