name: Merge Bot   

on:
  pull_request:
    branches: [ josh-branch, jacob-branch, dev-branch ]
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: false
        reviewers: false
        labels: automerge
        blocking_labels: do not merge
        checks_enabled: false
        method: merge
        delete_source_branch: false
